### ISSUE TITLE
Newsday no longer downloads 

### ISSUE THREAD

**Issue by Jgrahamiii** [adamantoise/robocrosswords#13]
As of 7/1/2018 keeps downloading 6/30 Newsday puzzle everyday.

**Comment by adamantoise** [comment]
There was an issue on the publisher's end.  They've since resolved it, and the Newsday puzzle now downloads correctly.

**Comment by Jgrahamiii** [comment]
Thanks!  Saw that. Any chance to amen app so that if you are currently filling an Across answer, the listed Down clue updates as the cursor moves boxes and vice versa??  My only gripe with the app. Thanks -John.

John M Graham III
Sent from my iPhone

On Jul 9, 2018, at 1:11 AM, Adam Rosenfield <notifications@github.com<mailto:notifications@github.com>> wrote:


There was an issue on the publisher's end. They've since resolved it, and the Newsday puzzle now downloads correctly.
